{{
  config(materialized='view')
}}

-- Bronze input: data/raw/ont_spain/<snapshot_date>/ont_national.csv
-- Generated by dbt_project/analyses/ont_spain_pdf_to_csv.py from the ONT
-- annual balance report PDF. One row per year, Spain national totals.
--
-- country_iso3 and country_name are hardcoded: ONT publishes Spain data only.

WITH raw AS (
    SELECT
        TRY_CAST(year AS INTEGER)               AS report_year,
        TRY_CAST(total_transplants AS INTEGER)  AS total_transplants,
        TRY_CAST(deceased_donors AS INTEGER)    AS deceased_donors,
        TRY_CAST(living_donors AS INTEGER)      AS living_donors,
        filename                                AS source_filename
    FROM read_csv_auto(
        '{{ env_var("TRANSPLANT_ATLAS_RAW_ROOT", "../data/raw") }}/ont_spain/*/ont_national.csv',
        filename=true,
        ignore_errors=false
    )
)

SELECT
    CAST('ESP' AS VARCHAR)                                              AS country_iso3,
    CAST('Spain' AS VARCHAR)                                           AS country_name,
    raw.report_year,
    raw.total_transplants,
    raw.deceased_donors,
    raw.living_donors,
    CAST('ONT' AS VARCHAR)                                             AS source,
    {{ snapshot_date_from_filename('raw.source_filename') }}::DATE     AS snapshot_date
FROM raw
WHERE raw.report_year BETWEEN 1990 AND EXTRACT(YEAR FROM CURRENT_DATE)
  AND raw.total_transplants IS NOT NULL
