{{
  config(materialized='view')
}}

-- Bronze input: data/raw/eurotransplant/<snapshot_date>/et_national.csv
-- Generated by dbt_project/analyses/eurotransplant_html_to_csv.py from two
-- Eurotransplant Statistics Library HTML reports:
--   - Report 11034 (deceased donors, absolute counts)
--   - Report 10821-33157 (transplants per million population, by donor type)
--
-- Coverage: AUT, BEL, HRV, DEU, HUN, NLD, SVN (2016-present).
-- Luxembourg is excluded; its sample size is too small for pmp reporting.
-- total_transplants is back-calculated from pmp × World Bank population.

WITH raw AS (
    SELECT
        TRY_CAST(year AS INTEGER)               AS report_year,
        TRIM(country_iso3)                      AS country_iso3,
        TRIM(country_name)                      AS country_name,
        TRY_CAST(total_transplants AS INTEGER)  AS total_transplants,
        TRY_CAST(deceased_donors AS INTEGER)    AS deceased_donors,
        TRY_CAST(living_donors AS INTEGER)      AS living_donors,
        filename                                AS source_filename
    FROM read_csv_auto(
        '{{ env_var("TRANSPLANT_ATLAS_RAW_ROOT", "../data/raw") }}/eurotransplant/*/et_national.csv',
        filename=true,
        ignore_errors=false
    )
)

SELECT
    raw.country_iso3,
    raw.country_name,
    raw.report_year,
    raw.total_transplants,
    raw.deceased_donors,
    raw.living_donors,
    CAST('Eurotransplant' AS VARCHAR)                                    AS source,
    {{ snapshot_date_from_filename('raw.source_filename') }}::DATE       AS snapshot_date
FROM raw
WHERE raw.report_year BETWEEN 1990 AND EXTRACT(YEAR FROM CURRENT_DATE)
  AND raw.total_transplants IS NOT NULL
