{{
  config(materialized='view')
}}

-- Bronze input: data/raw/scandiatransplant/<snapshot_date>/sctp_national.csv
-- Generated by dbt_project/analyses/scandiatransplant_xlsx_to_csv.py from the
-- Scandiatransplant annual XLSX report (one sheet per year).
--
-- Coverage: DNK, SWE, NOR, FIN, ISL, EST (1990-present).
-- total_transplants = sum of solid-organ and islet allograft counts from the XLSX.
-- deceased_donors = "Total Utilized deceased donors" row (exact count).
-- living_donors = sum of living-donor kidney and liver rows.

WITH raw AS (
    SELECT
        TRY_CAST(year AS INTEGER)               AS report_year,
        TRIM(country_iso3)                      AS country_iso3,
        TRIM(country_name)                      AS country_name,
        TRY_CAST(total_transplants AS INTEGER)  AS total_transplants,
        TRY_CAST(deceased_donors AS INTEGER)    AS deceased_donors,
        TRY_CAST(living_donors AS INTEGER)      AS living_donors,
        filename                                AS source_filename
    FROM read_csv_auto(
        '{{ env_var("TRANSPLANT_ATLAS_RAW_ROOT", "../data/raw") }}/scandiatransplant/*/sctp_national.csv',
        filename=true,
        ignore_errors=false
    )
)

SELECT
    raw.country_iso3,
    raw.country_name,
    raw.report_year,
    raw.total_transplants,
    raw.deceased_donors,
    raw.living_donors,
    CAST('Scandiatransplant' AS VARCHAR)                                  AS source,
    {{ snapshot_date_from_filename('raw.source_filename') }}::DATE        AS snapshot_date
FROM raw
WHERE raw.report_year BETWEEN 1990 AND EXTRACT(YEAR FROM CURRENT_DATE)
  AND raw.total_transplants IS NOT NULL
  AND raw.total_transplants > 0
